spectool/README.md
Readme based on https://mailarchive.ietf.org/arch/msg/cellar/7g4t_MetEmSxmJToGDbG_aXt52s
=> initial commit of spectools README

spectool/ebmlschema2drupaltable.xsl
run via `xsltproc ebmlschema2drupaltable.xsl specdata.xml`
=> ebmlschema2drupaltable.xsl: initial commit

corec/corec/helpers/parser/parser2.c, spectool/data2lib.c, spectool/data2lib2.c, spectool/data2spec.c, spectool/spec2data.c, spectool/spec_element.c, spectool/spec_element.h
Handle the path and other new elements
=> Update the spectools to use the new ebml_specification.xml format

spectool/data2lib.c
… as done two lines earlier for GitHub
=> use `https` also for the website

libebml2/ebmlbinary.c, libebml2/ebmldate.c, libebml2/ebmlmaster.c, libebml2/ebmlnumber.c, libebml2/ebmlstring.c
Also handle incorrect data reading as errors. The file will not be readable, just as when there's an Out Of Memory error.
=> Fix misc potential read overflow

README.txt
The mkclean and mkvalidator packages have been updated but not the readme at the root
Fixes #77
=> simplify the main Readme.txt

spectool/schema_2_matroska_sem_c.xsl
valid WebM elements now have to be explictly set. So adding new elements won't
automatically add them as valid in WebM.
=> spectool: fix valid webm detection

spectool/schema_2_kaxsematic_cpp.xsl, spectool/schema_2_kaxsematic_h.xsl
=> Libmatroska enums

spectool/schema_2_kaxsematic_cpp.xsl, spectool/schema_2_matroska_sem_c.xsl
In libmatroska2 this should be a separate flag in the semantic (#92).
=> spectool: allow multiple copies of recurring elements

.github/workflows/libmatroska-semantic.yaml, .github/workflows/libmatroska2-semantic.yaml, README.md
If possible it should be ran each time ebml_schema.xml is updated in https://github.com/Matroska-Org/foundation-source
Fixes #99
=> add code generator to check regression, missing updates

.github/workflows/libmatroska-semantic.yaml, .github/workflows/libmatroska2-semantic.yaml
So we can detect when something is broken
=> run the code generator automatically once a week

.github/workflows/libmatroska-semantic.yaml, spectool/schema_2_kaxsemantic_cpp.xsl, spectool/schema_2_kaxsemantic_h.xsl
=> fix file name of XSL files for libMatroska

mkclean/ChangeLog.txt, mkclean/mkclean.c
it's useless to recover damaged files
=> mkclean: don't write the Cluster Position

mkclean/regression/mkcleanreg.py
Now we can document nicely the regression file(s).
=> mkclean: allow empty lines in mkcleanreg files

libmatroska2/matroska2/matroska_sem.h, spectool/schema_2_kaxsemantic_h.xsl, spectool/schema_2_matroska_sem_h.xsl
See https://github.com/Matroska-Org/libmatroska/pull/99
=> spectools: clean IETF references in semantics enums

spectool/schema_2_kaxsemantic_cpp.xsl, spectool/schema_2_kaxsemantic_h.xsl
And remove EBML2 special case in libmatroska
=> Move KaxPrevUID/KaxPrevUID in KaxSemantic

spectool/schema_2_kaxsemantic_cpp.xsl
Only master elements can and only very few.
=> Keep information about elements that can have an infinite size

spectool/schema_2_kaxsemantic_h.xsl
Corresponds to https://github.com/Matroska-Org/libmatroska/pull/122
=> Switch to the ShouldWrite API to select which elements to write

spectool/schema_2_kaxsemantic_h.xsl
=> don't force the libebml namespace in KaxSemantic.h

spectool/schema_2_kaxsemantic_h.xsl
Necessary changes for https://github.com/Matroska-Org/libmatroska/pull/134
=> declare elements that have a default value accordingly

spectool/schema_2_kaxsemantic_cpp.xsl, spectool/schema_2_kaxsemantic_h.xsl
On top of https://github.com/Matroska-Org/foundation-source/pull/133
=> Rename *Timecode* class and debug names to *Timestamp*

spectool/schema_2_kaxsemantic_cpp.xsl
Branch used to generate https://github.com/Matroska-Org/libmatroska/pull/148
=> [RFC] keep the min/max/webm/divx information for each element 

mkclean/mkclean.c
It's not a mandatory element and doesn't have a default value.
=> mkclean: don't assume the Cluster PrevSize is present

.github/workflows/generate-tools-bin.yaml, .github/workflows/generate-tools.yaml, CMakeLists.txt
Similar to what is done in libebml/libmatroska.
=> enable more warnings in the CI

libmatroska2/CMakeLists.txt, libmatroska2/matroskamain.c
=> libmatroska2: use the library/include found for zlib
