- spectool/specdata.xml
> Set VOID Element as multiple in Matroska spec

- spectool/data2lib2.c
This is the same fix as d294a5e2801e560cd3bbb37951c95d5aff6c8bb0.
> data2lib2: Fix build with newer GCCs

- corec/corec/portab.h
strXXX is supposed to be reserved in ISO C but POSIX just uses that word.
MSVC (and its clang friend) doesn't like it.
> use _strdup instead of strdup with MSVC

- corec/corec/helpers/CMakeLists.txt
- corec/corec/helpers/charconvert/charconvert_linux.c
- corec/tests/CMakeLists.txt
CMake being CMake, it's not possible to propagate iconv linking through the INTERFACE `target_link_libraries`. It has to be set on all real libraries using the INTERFACE directly or indirectly.
Fixes #72
> Fix cygwin linking

- corec/corec/helper.h
- corec/corec/portab.h
- libebml2/ebml2/ebml.h
- libebml2/ebmlbinary.c
- libebml2/ebmlcrc.c
- libebml2/ebmldate.c
- libebml2/ebmlelement.c
- libebml2/ebmlmain.c
- libebml2/ebmlmaster.c
- libebml2/ebmlnumber.c
- libebml2/ebmlstring.c
- libebml2/ebmlvoid.c
- libebml2/test/ebmltree.c
- libmatroska2/matroska2/matroska.h
- libmatroska2/matroskablock.c
- libmatroska2/matroskamain.c
- libmatroska2/test/mkvtree.c
- mkclean/mkclean.c
- mkparts/mkparts.c
- mkvalidator/mkvalidator.c
And some code/warning cleaning.
Now reading in mkclean/mkvalidator is tightly linked to the specified profile.
> Make tighter use of profiles when reading/writing

- libmatroska2/MatroskaParser/MatroskaParser.c
- libmatroska2/MatroskaParser/MatroskaParser.h
- libmatroska2/matroska2/matroska.h
- libmatroska2/matroska2/matroska_classes.h
- libmatroska2/matroskablock.c
- libmatroska2/matroskamain.c
- mkclean/mkclean.c
- mkvalidator/mkvalidator.c
The `--timecodescale` option of mkclean remains for now.
Given noone outside of this code tree is using libmatroska2 that shouldn't be a problem.
> libmatroska2: rename all timecode API's to timestamp

- libmatroska2/matroska_sem.c
Until there is a recurring flag in libebml2 (#92) we must assume the element is ok multiple times.
> libmatroska2: fix unique elements that can be recurring

- spectool/schema_2_kaxsematic_cpp.xsl
- spectool/schema_2_kaxsematic_h.xsl
Some element names changed.
Generates https://github.com/Matroska-Org/libmatroska/pull/61 properly (without v5 elements)
> spectool: fix KaxSemantic generator with latest Schema

- libmatroska2/matroska2/matroska.h
- mkclean/mkclean.c
- mkclean/regression/mkcleanreg.py
- mkvalidator/mkvalidator.c
In case some files with v5 DocTypeVersion appears we need to be able to validate (or invalidate) them.
~~Draft as it sits on top of #89~~
> libmatroska2: add support for Matroska v5 reading/writing

- mkclean/mkclean.c
This is the default on Linux and MacOS (and recently on Windows AFAIK)
> mkclean: read non-wide filenames as UTF-8

- .github/workflows/libmatroska-semantic_1x.yaml
- README.md
- spectool/schema_2_kaxsemantic_cpp_1x.xsl
- spectool/schema_2_kaxsemantic_h_1x.xsl
As 2.0 evolves we can't keep the same generated code on both sides. Especially as the class names will change for https://github.com/Matroska-Org/libmatroska/issues/137
> Generate libmatroska v1.x semantic separately

- spectool/schema_2_kaxsemantic_cpp.xsl
since b0d8c7b77f0c29b96351099adf6691df06ebb860
And fix missing ShouldWrite usage that was switched in 4125c26c50388a76f036494901b0c0d0f454813f.
> fix libebml namespace usage after removing using namespace

- spectool/schema_2_kaxsemantic_h.xsl
String may have size constraints in EBML but we don't use that.
> spectools: Use a macro to set the length constraint on binary elements

- spectool/schema_2_kaxsemantic_cpp.xsl
We don't do anything more than the default ones.
Corresponds to https://github.com/Matroska-Org/libmatroska/pull/160
> use the regular constructor for KaxTrackEntry

- spectool/schema_2_kaxsemantic_h.xsl
Used in https://github.com/Matroska-Org/libmatroska/pull/112
> spectools: clean the references in enum titles

- spectool/schema_2_kaxsemantic_cpp.xsl
passing temporary objects by reference is bogus.
> spectools: use hardcoded profiles for Matroska/WebM/DivX versioning

- corec/corec/helpers/zlib/CMakeLists.txt
- corec/corec/portab.h
- libmatroska2/matroska2/matroska.h
- libmatroska2/matroskamain.c
- mkclean/mkclean.c
Needed by #150
And some corec removal.
> libmatroska: misc. compression cleanup

- .github/workflows/generate-tools.yaml
- .github/workflows/libmatroska-semantic.yaml
- .github/workflows/libmatroska-semantic_1x.yaml
- .github/workflows/libmatroska2-semantic.yaml
So we don't get failed build on semantic of libmatroska when we're not changing anything about that.
That will build less/faster as well.
> CI: avoid build spectools/tools when not necessary

- libmatroska2/CMakeLists.txt
As said in RFC9559, we should not compress to bzlib and lzo anymore. The code already only supports decompression.
Let's reflect this in the option text.
> libmatroska2: change decompression options

- corec/corec/helper.h
- libmatroska2/CMakeLists.txt
- libmatroska2/matroskamain.c
- mkclean/regression/mkcleanreg.py
- mkclean/regression/regression.mkc
Fix recent bugs, update the regression file with elements removed in recent semantic.
Also fix the win32 static build.
> mkclean: fix regression checks

- libmatroska2/matroskamain.c
- mkclean/regression/regression.mkc
The regression file is back to normal (on Windows).
> mkclean: update regression file with zlib not compiled with FASTEST

- CMakeLists.txt
- corec/corec/CMakeLists.txt
- corec/corec/helpers/CMakeLists.txt
- corec/corec/helpers/file/streams.h
- corec/corec/node/node.c
- corec/corec/node/nodetools.h
- corec/tests/CMakeLists.txt
- corec/tests/file_test.c
- corec/tests/node_test.c
- libebml2/CMakeLists.txt
- libebml2/test/ebmltree.c
- libmatroska2/test/mkvtree.c
- mkclean/mkclean.c
- mkparts/mkparts.c
- mkvalidator/mkvalidator.c
The corec library doesn't have different compilation options depending on the mk<tool> compiled. We can use a single (static) library for corec.
Plus more compilation error checks and code cleaning.
> only build corec files once

- libmatroska2/matroskamain.c
It's used to skip the data no matter what.
> libmatroska2: always initialize the lace FrameSize

- mkclean/mkclean.c
The global error is set to -46 when the happens.
> mkclean: use a local error to check remuxing error

- corec/corec/portab.h
- libebml2/ebmlmaster.c
- mkclean/mkclean.c
Some are legit, some are MSVC bogus complains.
> mkclean: avoid using uninitialized variables

- libmatroska2/matroskamain.c
The part of the Matroska specifications that claimed that Blocks from a BlockGroup with duration zero are no keyframes has been dropped in [9313a00f7391a285f95e9d6f0a5f8f3f80ed4779](https://github.com/ietf-wg-cellar/matroska-specification/pull/207). This commit brings libmatroska2 in line with this change.
The earlier version e.g. made mkvalidator warn about files muxed by FFmpeg that contained pgs subtitles (which are muxed as zero-duration subtitles, which is spec-compliant).
rebased version of #40
> libmatroska2: 0 duration frames can be keyframes

- libebml2/ebmlmaster.c
Caught by the `CONFIG_DEBUG_LEAKS` compiler option.
> libebml2: fix misc. leaks

- CMakeLists.txt
The command line tools should not use things specific to recent macOS. So they can run on older Intel macOS as well.
> CMake: target older macOS

- .github/workflows/codeql-analysis.yml
v1 is long deprecated
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
> CI: switch to codeql v2

- corec/corec/helper.h
- corec/corec/helpers/parser/parser2.c
- corec/corec/helpers/parser/strtypes.c
- libmatroska2/CMakeLists.txt
- libmatroska2/matroska_config.h.in
- libmatroska2/matroskablock.c
- libmatroska2/tremor/block.c
- libmatroska2/tremor/info.c
- libmatroska2/tremor/os.h
- libmatroska2/tremor/sharedbook.c
- mkclean/CMakeLists.txt
- mkclean/mkclean.c
- mkclean/regression/mkcleanreg.py
- mkclean/regression/regression.mkc
- mkvalidator/mkvalidator.c
We can use the extra data to find the original frequency.
Properly enable tremor usage as intended.
Plus some mkcleanreg fixups.
> mkvalidator: fix Vorbis 0 SamplingFrequency

- CMakeLists.txt
- corec/corec/array/array.c
- corec/corec/array/array.h
- corec/corec/memheap.h
- mkclean/mkclean.c
Let the compiler detect suspicious casts.
> corec: check/fix pointer alignment

- libmatroska2/matroska2/matroska_sem.h
- spectool/schema_2_kaxsemantic_cpp.xsl
- spectool/schema_2_kaxsemantic_cpp_1x.xsl
- spectool/schema_2_kaxsemantic_h.xsl
- spectool/schema_2_kaxsemantic_h_1x.xsl
- spectool/schema_2_matroska_sem_h.xsl
Don't break the libmatroska 1.0 API/ABI (apart from some enums that were unused).
> spectool: update/clean the semantic outputs based on RFC 9559
